<?php

/**
 * @file
 * Adds support for serializing entities to JSON-LD / Islandora CLAW Project.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function jsonld_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.hal':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= t('<p><a href=":jsonld_spec">JSON-LD</a>, or JavaScript Object Notation for Linked Data, is
        a method of encoding Linked Data using JSON.</p>', [':jsonld_spec' => 'http://json-ld.org/spec/latest/json-ld-syntax/']);
      return $output;
  }
}
