<?php

/**
 * @file
 * Adds support for serializing entities to JSON-LD / Islandora Project.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function jsonld_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.hal':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= t('<p><a href=":jsonld_spec">JSON-LD</a>, or JavaScript Object Notation for Linked Data, is
        a method of encoding Linked Data using JSON.</p>', [':jsonld_spec' => 'http://json-ld.org/spec/latest/json-ld-syntax/']);
      return $output;
  }
}

/**
 * Implements hook_rdf_namespaces().
 */
function jsonld_rdf_namespaces() {
  $config = \Drupal::config('jsonld.settings');
  $namespace_config = $config->get('rdf_namespaces');
  if (!is_array($namespace_config)) {
    // No namespaces have been configured, return empty.
    return [];
  }
  $namespaces = [];
  foreach ($namespace_config as $namespace) {
    $namespaces[$namespace['prefix']] = $namespace['namespace'];
  }
  return $namespaces;
}

/**
 * Implements hook_jsonld_field_mappings().
 */
function jsonld_jsonld_field_mappings() {
  return [
    "comment" => [
      "@type" => "xsd:string",
    ],
    "datetime" => [
      "@type" => "xsd:dateTime",
    ],
    "file" => [
      "@type" => "@id",
    ],
    "image" => [
      "@type" => "@id",
    ],
    "link" => [
      "@type" => "xsd:anyURI",
    ],
    "list_float" => [
      "@type" => "xsd:float",
      "@container" => "@list",
    ],
    "list_integer" => [
      "@type" => "xsd:int",
      "@container" => "@list",
    ],
    "list_string" => [
      "@type" => "xsd:string",
      "@container" => "@list",
    ],
    "path" => [
      "@type" => "xsd:anyURI",
    ],
    "text" => [
      "@type" => "xsd:string",
    ],
    "text_with_summary" => [
      "@type" => "xsd:string",
    ],
    "text_long" => [
      "@type" => "xsd:string",
    ],
    "uuid" => [
      "@type" => "xsd:string",
    ],
    "uri" => [
      "@type" => "xsd:anyURI",
    ],
    "language" => [
      "@type" => "xsd:language",
    ],
    "string_long" => [
      "@type" => "xsd:string",
    ],
    "changed" => [
      "@type" => "xsd:dateTime",
    ],
    "map" => "xsd:",
    "boolean" => [
      "@type" => "xsd:boolean",
    ],
    "email" => [
      "@type" => "xsd:string",
    ],
    "integer" => [
      "@type" => "xsd:int",
    ],
    "decimal" => [
      "@type" => "xsd:decimal",
    ],
    "created" => [
      "@type" => "xsd:dateTime",
    ],
    "float" => [
      "@type" => "xsd:float",
    ],
    "entity_reference" => [
      "@type" => "@id",
    ],
    "timestamp" => [
      "@type" => "xsd:dateTime",
    ],
    "string" => [
      "@type" => "xsd:string",
    ],
    "password" => [
      "@type" => "xsd:string",
    ],
  ];
}
